# Generated by Django 5.1 on 2024-09-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_country_alter_adress_options_book_published_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
